# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'see.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 356)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 281, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_rooms = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_rooms.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_rooms.setFont(font)
        self.label_rooms.setToolTip("")
        self.label_rooms.setStyleSheet("margin-left : 20\n"
                                       "")
        self.label_rooms.setTextFormat(QtCore.Qt.PlainText)
        self.label_rooms.setScaledContents(False)
        self.label_rooms.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_rooms.setObjectName("label_rooms")
        self.verticalLayout_5.addWidget(self.label_rooms)
        self.label_Z = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_Z.setStyleSheet("margin-left : 20\n"
                                   "")
        self.label_Z.setObjectName("label_Z")
        self.verticalLayout_5.addWidget(self.label_Z)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kitchen_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.kitchen_room.setMouseTracking(True)
        self.kitchen_room.setTabletTracking(False)
        self.kitchen_room.setObjectName("kitchen_room")
        self.verticalLayout.addWidget(self.kitchen_room)
        self.sawmill_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.sawmill_room.setObjectName("sawmill_room")
        self.verticalLayout.addWidget(self.sawmill_room)
        self.bank_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.bank_room.setObjectName("bank_room")
        self.verticalLayout.addWidget(self.bank_room)
        self.lab_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.lab_room.setObjectName("lab_room")
        self.verticalLayout.addWidget(self.lab_room)
        self.forge_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.forge_room.setObjectName("forge_room")
        self.verticalLayout.addWidget(self.forge_room)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.start_rooms = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.start_rooms.setStyleSheet("")
        self.start_rooms.setObjectName("start_rooms")
        self.verticalLayout_5.addWidget(self.start_rooms)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_tablet = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_tablet.setFont(font)
        self.label_tablet.setStyleSheet("margin-left : 20")
        self.label_tablet.setObjectName("label_tablet")
        self.verticalLayout_6.addWidget(self.label_tablet)
        self.label_X = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_X.setStyleSheet("margin-left : 20\n"
                                   "")
        self.label_X.setObjectName("label_X")
        self.verticalLayout_6.addWidget(self.label_X)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.start_tablet = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.start_tablet.setObjectName("start_tablet")
        self.verticalLayout_6.addWidget(self.start_tablet)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 310, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.xxx()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_rooms.setText(_translate("MainWindow", "Просмотреть рекламу в комнатах"))
        self.label_Z.setText(_translate("MainWindow", "Ручное отключение ALT+Z"))
        self.kitchen_room.setText(_translate("MainWindow", "Кухня"))
        self.sawmill_room.setText(_translate("MainWindow", "Лесопилка"))
        self.bank_room.setText(_translate("MainWindow", "Банкир"))
        self.lab_room.setText(_translate("MainWindow", "Лаборатория"))
        self.forge_room.setText(_translate("MainWindow", "Кузница"))
        self.start_rooms.setText(_translate("MainWindow", "Старт"))
        self.label_tablet.setText(_translate("MainWindow", "Просмотреть рекламу на планшете"))
        self.label_X.setText(_translate("MainWindow", "Ручное отключение ALT+X"))
        self.start_tablet.setText(_translate("MainWindow", "Старт"))

    def xxx(self):
        self.start_rooms.clicked.connect(self.yyy)

    def yyy(self):
        print(self.kitchen_room.isChecked())
        print(self.sawmill_room.isChecked())
        print(self.bank_room.isChecked())
        print(self.lab_room.isChecked())
        print(self.forge_room.isChecked())


# def run_main_see():
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

# if __name__ == "__main__":
#     import sys
#
#     run_main()
