# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'see.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

from run_video import AdClicker


class Ui_MainWindow(object):

    def __init__(self):
        self.preview = AdClicker()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(304, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 281, 323))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_rooms = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_rooms.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_rooms.setFont(font)
        self.label_rooms.setToolTip("")
        self.label_rooms.setStyleSheet("margin-left : 20\n"
                                       "")
        self.label_rooms.setTextFormat(QtCore.Qt.PlainText)
        self.label_rooms.setScaledContents(False)
        self.label_rooms.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_rooms.setObjectName("label_rooms")
        self.verticalLayout_5.addWidget(self.label_rooms)
        self.label_Z = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_Z.setStyleSheet("margin-left : 20\n"
                                   "")
        self.label_Z.setObjectName("label_Z")
        self.verticalLayout_5.addWidget(self.label_Z)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kitchen_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.kitchen_room.setMouseTracking(True)
        self.kitchen_room.setTabletTracking(False)
        self.kitchen_room.setObjectName("kitchen_room")
        self.verticalLayout.addWidget(self.kitchen_room)
        self.sawmill_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.sawmill_room.setObjectName("sawmill_room")
        self.verticalLayout.addWidget(self.sawmill_room)
        self.bank_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.bank_room.setObjectName("bank_room")
        self.verticalLayout.addWidget(self.bank_room)
        self.lab_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.lab_room.setObjectName("lab_room")
        self.verticalLayout.addWidget(self.lab_room)
        self.forge_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.forge_room.setObjectName("forge_room")
        self.verticalLayout.addWidget(self.forge_room)
        self.zal_room = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.zal_room.setObjectName("zal_room")
        self.verticalLayout.addWidget(self.zal_room)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_rooms = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.start_rooms.setStyleSheet("")
        self.start_rooms.setObjectName("start_rooms")
        self.horizontalLayout_3.addWidget(self.start_rooms)
        self.stop_rooms = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.stop_rooms.setObjectName("stop_rooms")
        self.horizontalLayout_3.addWidget(self.stop_rooms)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label_tablet = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_tablet.setFont(font)
        self.label_tablet.setStyleSheet("margin-left : 20")
        self.label_tablet.setObjectName("label_tablet")
        self.verticalLayout_6.addWidget(self.label_tablet)
        self.label_X = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_X.setStyleSheet("margin-left : 20\n"
                                   "")
        self.label_X.setObjectName("label_X")
        self.verticalLayout_6.addWidget(self.label_X)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_tablet = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.start_tablet.setObjectName("start_tablet")
        self.horizontalLayout_4.addWidget(self.start_tablet)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 304, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_rooms.setText(_translate("MainWindow", "Просмотреть рекламу в комнатах"))
        self.label_Z.setText(_translate("MainWindow", "Ручное отключение ALT+Z"))
        self.kitchen_room.setText(_translate("MainWindow", "Кухня"))
        self.sawmill_room.setText(_translate("MainWindow", "Лесопилка"))
        self.bank_room.setText(_translate("MainWindow", "Банкир"))
        self.lab_room.setText(_translate("MainWindow", "Лаборатория"))
        self.forge_room.setText(_translate("MainWindow", "Кузница"))
        self.zal_room.setText(_translate("MainWindow", "Спорт зал"))
        self.start_rooms.setText(_translate("MainWindow", "Старт"))
        self.stop_rooms.setText(_translate("MainWindow", "Стоп"))
        self.label_tablet.setText(_translate("MainWindow", "Просмотреть рекламу на планшете"))
        self.label_X.setText(_translate("MainWindow", "Ручное отключение ALT+X"))
        self.start_tablet.setText(_translate("MainWindow", "Старт"))
        self.pushButton.setText(_translate("MainWindow", "Стоп"))

    def xxx(self):
        """Нажатие кнопки просмотр рекламы в комнатах"""
        self.start_rooms.clicked.connect(self.yyy)


    def yyy(self):
        # self.start_rooms.setText('Stop')

        self.preview.KITCHEN_ROOM = self.kitchen_room.isChecked()
        self.kitchen_room.setEnabled(False)

        self.preview.LAB_ROOM = self.lab_room.isChecked()
        self.lab_room.setEnabled(False)
        self.preview.BANK_ROOM = self.bank_room.isChecked()
        self.bank_room.setEnabled(False)
        # self.preview.ZAL_ROOM = self..isChecked()
        self.preview.JOINERY_ROOM = self.sawmill_room.isChecked()
        self.kitchen_room.setEnabled(False)
        # #
        # self.watch_ads()

    def watch_ads(self):
        self.start_rooms.setText('Stop')
        while True:
            if self.preview.KITCHEN_ROOM:
                self.preview.kitchen_rooms()
            elif self.preview.LAB_ROOM:
                self.preview.laboratory_room()
            elif self.preview.JOINERY_ROOM:
                self.preview.joinery_room()
            elif self.preview.ZAL_ROOM:
                self.preview.zal_room()
            elif self.preview.BANK_ROOM:
                self.preview.bank_room()
